# Generated by Django 2.2.4 on 2020-04-11 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_state'),
    ]

    operations = [
        migrations.DeleteModel(
            name='state',
        ),
    ]
